### ISSUE TITLE
User can view detailed overview of each waste site

### ISSUE THREAD

**Issue by jwld** [FACN1/litter-app#10]
- [x] User can view image of a WS on post page (#28)
- [x] User can view details of the WS (#29)
- [x] User can click through from a post page to a map of its location (#25)
- [x] User can click back from location view to post details (#26)
