### ISSUE TITLE
Browse a map of waste sites

### ISSUE THREAD

**Issue by jwld** [FACN1/litter-app#11]
#9

- [x] Add LeafletJS map to browse page (#17)
- [x] Add some dummy markers to map (#21)
- [x] Configure map to default to user's location (#24)
- [x] Create DB table for map markers (#71)
- [x] Populate map with markers using DB data (#72)

**As a user interested in helping with cleanups**
> I want to be able to browse a map

> So that I can see all the reported waste sites
