### ISSUE TITLE
Submit form data to DB and redirect to post upon submission

### ISSUE THREAD

**Issue by edgarfinn** [FACN1/litter-app#20]
#8 
As a user who has just submitted a report of a WS

> I want to be redirected to an overview page of my new submission

> So that I can see what my submission looks like

SUBMIT BUTTON ONCLICK:
- [x] Make dbQuery inserting submission to database (#36)
- [x] Upload linked image to S3 (#45)
- [x] Redirect to specific post page (#44).
