### ISSUE TITLE
User can easily navigate the app

### ISSUE THREAD

**Issue by jwld** [FACN1/litter-app#37]
- [x] View logo and description of app on landing page (#39)
- [x] Navigation buttons on landing page (#40)
- [x] Create nav bar partial (#50)
