### ISSUE TITLE
User can report a waste site

### ISSUE THREAD

**Issue by edgarfinn** [FACN1/litter-app#8]
- [x] User can navigate from home page to Report page (#12)
- [x] User can submit location of WS (#14)
- [x] User can upload an image of the WS to the browser (#16)
- [x] User can submit details of a WS (#18)
- [x] User is redirected to WS post page upon submission (#20)
