### ISSUE TITLE
User can browse a map of all waste sites

### ISSUE THREAD

**Issue by edgarfinn** [FACN1/litter-app#9]
- [x] Browse a map of waste sites (#11)
- [x] Search by postcode or address (#13)
- [x] Navigate to a specific WS page (#15)
- [x] Navigate to report page from browse page (#22)
